[workspace]
members = [
    "Editor",
    "Graph",
    "uilib",
    "Imaginarium"
]

resolver = "2"

[workspace.dependencies]
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
uuid = { version = "*", features = ["v4", "serde"] }
anyhow = "*"
wgpu = "*"
bytemuck = { version = "*", features = ["derive"] }
pollster = "*"
