[workspace]
members = [
    "Editor",
    "Graph",
    "uilib",
    "Imaginarium"
]

resolver = "2"

[workspace.dependencies]
graph_lib = { path = "./Graph", package = "graph" }
egui_node_graph = { path = "./egui_node_graph/egui_node_graph" }

serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
serde_json = "*"
uuid = { version = "*", features = ["v4", "serde"] }
anyhow = "*"
wgpu = "*"
bytemuck = { version = "*", features = ["derive"] }
pollster = "*"
tiff = "*"
png = "*"
image = "*"
num-traits = "*"
winit = "*"
glam = "*"
glyph_brush = "*"
mlua = { version = "*", features = ["lua54", "vendored"] }
egui_file = "*"
eframe = { version = "*", features = ["wgpu"] }
