[workspace]
members = [
    "Editor",
    "Graph",
    "uilib"
]

resolver = "2"

[workspace.dependencies]
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
uuid = { version = "*", features = ["v4", "serde"] }
anyhow = "*"
