[package]
name = "graph"
version = "0.1.1"
edition = "2021"
description = "A graph library for Nodeshop"

[lib]
name = "graph"
crate-type = ["lib"]

[dependencies]
mlua = { version = "*", features = ["lua54", "vendored"] }
serde = { workspace = true }
serde_yaml = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }

