[package]
name = "graph"
version = "0.1.1"
edition = "2021"
description = "A graph library for Nodeshop"

[lib]
name = "graph"
crate-type = ["lib"]

[features]
default = []
opencl = ["ocl"]

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
mlua = { version = "*", features = ["lua54", "vendored"] }
ocl = { version = "*", optional = true }
uuid = { version = "*", features = ["v4", "macro-diagnostics", "serde"] }
anyhow = "*"
