[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
mlua = { version = "0.8", features = ["lua54", "vendored"] }
#ocl = "0.19"


[dependencies.uuid]
version = "1"
features = [
    "v4",                # Lets you generate random UUIDs
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]
