[package]
name = "nodeshop"
version = "0.1.0"
edition = "2021"

[features]
default = []
opencl = ["graph/opencl"]

[dependencies]
graph = { path = "../Graph" }
# uilib = { path = "../uilib" }

eframe = "0.21.3"
egui_node_graph =  { path = "../../egui_node_graph/egui_node_graph" }
anyhow = "*"
