[package]
name = "editor"
version = "0.1.0"
edition = "2021"
description = "Nodeshop GUI App"

[features]
default = []
opencl = ["graph/opencl"]

[dependencies]
graph = { path = "../Graph" }
iced = { version = "0.9.0", features = ["canvas"] }
