[package]
name = "nodeshop"
version = "0.1.0"
edition = "2021"

[features]
default = []
opencl = ["graph/opencl"]

[dependencies]
graph = { path = "../Graph" }
wgpu = "0"
winit = "0"
glam = "0"
pollster = "0"
bytemuck = { version = "1", features = ["derive"] }
