[package]
name = "nodeshop"
version = "0.1.0"
edition = "2021"

[features]
default = []
opencl = ["graph/opencl"]

[dependencies]
graph = { path = "../Graph" }
wgpu = { version = "0" }
winit = { version = "0" }
bytemuck = { version = "1", features = ["derive"] }
glam = "0"
async-executor = "1"
pollster = "0"
