[package]
name = "uilib"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { workspace = true }
bytemuck = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
glyph_brush = { workspace = true }

