name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest ]
        rust: [ stable ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build graph
        run: cargo build --manifest-path=Graph/Cargo.toml --verbose

      - name: Run graph tests
        run: cargo test --manifest-path=Graph/Cargo.toml --verbose

      - name: Build editor
        run: cmake -S ./Editor -B ./Editor/build && cmake --build ./Editor/build
